// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYrUfqmTQL4xVvXThb5Mt-yEDA-JvTw8',
    appId: '1:301003572226:web:692e15fdce71a682ab131b',
    messagingSenderId: '301003572226',
    projectId: 'push-notification-exampl-8490a',
    authDomain: 'push-notification-exampl-8490a.firebaseapp.com',
    storageBucket: 'push-notification-exampl-8490a.appspot.com',
    measurementId: 'G-1X68G449V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvdonbj5IsH9XcJG4F0tS_6NjzE4TphU',
    appId: '1:301003572226:android:d09e47d8aa679f7bab131b',
    messagingSenderId: '301003572226',
    projectId: 'push-notification-exampl-8490a',
    storageBucket: 'push-notification-exampl-8490a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWFTlNnkimqMSZs-cKka1-cl_uyHKeu7g',
    appId: '1:301003572226:ios:801d503c24015ab6ab131b',
    messagingSenderId: '301003572226',
    projectId: 'push-notification-exampl-8490a',
    storageBucket: 'push-notification-exampl-8490a.appspot.com',
    iosClientId: '301003572226-oaah4u2v43i1323fm79o9ou078p6cm1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
